### ISSUE TITLE
DEBUG floating point formatting not working for ESP8266

### ISSUE THREAD

**Issue by ghislainborremans** [rlogiacco/MicroDebug#1]
Hello 

maybe it is good to mention in the README that the printf is not working for formatting floating point numbers on ESP8266. 
This will eliminate unneccessary searching for other users.

**Comment by rlogiacco** [comment]
Does it work with all other formats?
Do you know of an alternative which works with floating points on ESP8266?
Can you pinpoint me to where this information is shared? I'm curious about the reason for it.

**Comment by ghislainborremans** [comment]
https://github.com/esp8266/Arduino/issues/73
