### ISSUE TITLE
#pragma message ("Microdebug ENABLED")

### ISSUE THREAD

**Issue by crisap94** [rlogiacco/MicroDebug#2]
The last update from the library makes appears this warnings that wasn't before.

In file included from src\Schedule.h:5:0,
from src\Schedule.cpp:1:
C:\Users\User\.platformio\lib\MicroDebug_ID465/FormattingSerialDebug.h:23:39: note: #pragma message: MicroDebug ENABLED
#pragma message("MicroDebug ENABLED")
^
In file included from src\Schedule.h:5:0,
from src\main.cpp:2:
C:\Users\User\.platformio\lib\MicroDebug_ID465/FormattingSerialDebug.h:23:39: note: #pragma message: MicroDebug ENABLED

Good library btw...

**Comment by rlogiacco** [comment]
That's intended and aims at letting you know from compiler output if you forgot to enable/disable debugging: do you find it annoying?

**Comment by rlogiacco** [comment]
BTW, I've found this is _pragma message_ thing seems used by other libraries as well to print out their version or compile-time switches status...

**Comment by crisap94** [comment]
Well not annoying but I tend to care about the warnings (it has saved me a
lot of times my code) and a clean compile always looks nicer.
